# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
#
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2

## Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - tixtix320@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
